package security

import (
	"fmt"
	"strings"

	"github.com/hadnu/lazy.go/pkg/config"
)

// GenerateCIWorkflow generates a GitHub Actions CI workflow YAML as a string.
// This is the programmatic version; the template-based version in templates/workflow.tmpl
// is what gets written to disk.
func GenerateCIWorkflow(cfg *config.ProjectConfig) string {
	var sb strings.Builder

	sb.WriteString("name: CI\n\non:\n  push:\n    branches: [main]\n  pull_request:\n    branches: [main]\n\njobs:\n")
	sb.WriteString("  test:\n    name: Test\n    runs-on: ubuntu-latest\n    steps:\n")
	sb.WriteString("      - uses: actions/checkout@v4\n")
	sb.WriteString("      - uses: actions/setup-go@v5\n        with:\n          go-version: \"1.22\"\n          cache: true\n")
	sb.WriteString("      - run: go mod download\n")
	sb.WriteString("      - run: go test -v -race -coverprofile=coverage.out ./...\n")

	if cfg.Features.StaticAnalysis {
		sb.WriteString("\n  lint:\n    name: Lint\n    runs-on: ubuntu-latest\n    steps:\n")
		sb.WriteString("      - uses: actions/checkout@v4\n")
		sb.WriteString("      - uses: actions/setup-go@v5\n        with:\n          go-version: \"1.22\"\n          cache: true\n")
		sb.WriteString("      - uses: golangci/golangci-lint-action@v6\n        with:\n          version: latest\n")
	}

	if cfg.Features.SAST {
		sb.WriteString("\n  security:\n    name: Security Scan\n    runs-on: ubuntu-latest\n    steps:\n")
		sb.WriteString("      - uses: actions/checkout@v4\n")
		sb.WriteString("      - uses: actions/setup-go@v5\n        with:\n          go-version: \"1.22\"\n          cache: true\n")
		sb.WriteString("      - run: go install golang.org/x/vuln/cmd/govulncheck@latest\n")
		sb.WriteString("      - run: govulncheck ./...\n")
		sb.WriteString("      - run: go install github.com/securego/gosec/v2/cmd/gosec@latest\n")
		sb.WriteString("      - run: gosec ./...\n")
	}

	return fmt.Sprintf("# Generated by lazy.go\n%s", sb.String())
}
