package config

import (
	"fmt"
	"os"
	"strings"

	"gopkg.in/yaml.v3"
)

// yamlProject mirrors ProjectConfig for YAML serialization.
type yamlFile struct {
	Project struct {
		Name        string `yaml:"name"`
		ModulePath  string `yaml:"module_path"`
		Description string `yaml:"description"`
		Author      string `yaml:"author"`
		Type        string `yaml:"type"`
		License     string `yaml:"license"`
		Visibility  string `yaml:"visibility"`
		Criticality string `yaml:"criticality"`
	} `yaml:"project"`
	Features Features     `yaml:"features"`
	GitHub   GitHubConfig `yaml:"github"`
}

// LoadFromYAML reads a lazygo.yml file and returns a ProjectConfig.
func LoadFromYAML(path string) (*ProjectConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading config file: %w", err)
	}

	var f yamlFile
	if err := yaml.Unmarshal(data, &f); err != nil {
		return nil, fmt.Errorf("parsing YAML: %w", err)
	}

	cfg := &ProjectConfig{
		Name:        f.Project.Name,
		ModulePath:  f.Project.ModulePath,
		Description: f.Project.Description,
		Author:      f.Project.Author,
		Type:        ProjectType(strings.ToLower(f.Project.Type)),
		License:     LicenseType(strings.ToLower(f.Project.License)),
		Visibility:  Visibility(strings.ToLower(f.Project.Visibility)),
		Criticality: CriticalityLevel(strings.ToLower(f.Project.Criticality)),
		Features:    f.Features,
		GitHub:      f.GitHub,
	}

	if err := Validate(cfg); err != nil {
		return nil, fmt.Errorf("invalid config: %w", err)
	}

	return cfg, nil
}

// ExportToYAML writes a ProjectConfig to a lazygo.yml file.
func ExportToYAML(cfg *ProjectConfig, path string) error {
	var f yamlFile
	f.Project.Name = cfg.Name
	f.Project.ModulePath = cfg.ModulePath
	f.Project.Description = cfg.Description
	f.Project.Author = cfg.Author
	f.Project.Type = string(cfg.Type)
	f.Project.License = string(cfg.License)
	f.Project.Visibility = string(cfg.Visibility)
	f.Project.Criticality = string(cfg.Criticality)
	f.Features = cfg.Features
	f.GitHub = cfg.GitHub

	data, err := yaml.Marshal(&f)
	if err != nil {
		return fmt.Errorf("marshalling config: %w", err)
	}

	header := "# Generated by lazy.go — https://github.com/hadnu/lazy.go\n"
	if err := os.WriteFile(path, append([]byte(header), data...), 0o644); err != nil {
		return fmt.Errorf("writing config file: %w", err)
	}

	return nil
}

// Validate checks that required ProjectConfig fields are set and valid.
func Validate(cfg *ProjectConfig) error {
	if cfg.Name == "" {
		return fmt.Errorf("project name is required")
	}
	if cfg.ModulePath == "" {
		return fmt.Errorf("module path is required")
	}
	validTypes := map[ProjectType]bool{}
	for _, t := range AllProjectTypes() {
		validTypes[t] = true
	}
	if !validTypes[cfg.Type] {
		return fmt.Errorf("unknown project type: %q", cfg.Type)
	}
	return nil
}
